sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- echo "This design module has no tests"
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: IH5lPh9w/w5Uc/sGeDzko3U4fJWoYaHuHaOFJdWt0iRnkHNH6LKt8tch1NL78WZOCBFCDvewvn5dSYjTPBb80X/n8QPqRjlhpnsSRLBqj0XmQf5JonoYFuo9yq3tAqi7xBh5hWilVIuUEechhQBA5maGdz79FNR/Z43gwEOStXlXHDdW8di3bkpkjkJTSQGzvD+1uEHLYc9dLe6dfaacwjyayvFYCy3CMUvhLk44rlVdHNoYjcaoMvXaXYu5G6AbsSRreQrq+lGlrNL3toB2DkmfFKom1HowqDAe6nAk61XyWleqdTNqplZLZufMVF2Railo1xxVbINoSgwxWHeOYqg4qGcsV1sz+DGsxU5t1S3tqGajGCH1WTBq+juNVMcAYSyG8QQZAws5DWLMOKe+YeHaXGT3zwHeHK9G85NBrzod57tMj7mc59ibI5Rm5huJLZJu9hP57Yujd9HO1dre9/dRPr+7e6a6GWxPIdG25ei+4ynfnDSQ8XrT5SZoAGhoSMzni9mHBiz7LrdG4uL3G0HYAkywOtnOYx30A0m8acGGwVWg79AzrSz2zFi8xAen53UUGTPrLcmIAykpg34l7iIH2DRK+bbb4PJez89z9UqjeN3L0H9rcqzpQusmRkG7W5YBfpv48UxlJ9ne0sI5GQGe2MJPdh5lJXuMUkSIujw=
  - secure: mL5m8y/m39zC5qULbwdGTIE4rI5CcdBxIfGZzfBNsypcAm9sTkSKVgXOuS6ku+NeeMOtLREjtlkVFY97Pbsk7Bpoy6n3ZBnNeCjxOeoYWBwKvXvQK3PU5QZT/54amUwbI5G2AyY2NuNVl5kmqTFBBReeuzD4aX7Z+eEGTdGz5TQMx1BMRNflVhD4ALyDvahjlRepz7RyDEk5M4WkZNjFKjPug2NUBzUlIjnS4d6hB+rhSEdR0BM6VOG+AzH6w54KN3lurJHnHFVL4hCMATHxKmGntKEaP14KM0keJ1Y/gPmmWzSX2uDQ7rncaklEZ5DbeowdgTd+mlPmsAC+GHilEjr75fIq8tuFfkNwrhgbI0QIDZL8x0wO/5pZG/xIJVNtSlMd3/Wiyahj3mTHALmIlB8XnPoxSCSOWAmIQmUl9zAY46XbfL5KLolCrccRYKQ8Bhy7pPZpG19uLrK2gDAhFDDqbzUUG5fCbLy/qsDQPMyW7NxcZ8JuZzd4X+wz+/G9kohb8OG1NArmdjN5Nt+agy7z9X4TdfeAPDpV1s1ovk3YP/ARqlGDrsTkMhKHTFiqYGohMMJxQ+Sm5rtubD/fUaRz3d2mp860n8+EwU5zwPQ/TGDeQCJq7VFZoZY0ceuG+/J8FuNRcTDgCNkqrGLJGuiHM2mvWUsRcPRfTWVfJX4=
  - secure: p/vXQ+PfH4rvdRoddC4hBI6HfivMh4t5XhsE2XZqEi0Y6blneIn0VRkUHYyFY/XheijSWZ9grUOBtK+PGkosbmvIEI9I0KbAj4LBXthHyggTCMj8FElgcdFZd5zdD9lO6S/JJwvjTHmt5Q7RMg3fAo80MS71WBJAxApWwmm4a8XcJLTxP/Xla4jNhhAHLSLdFbsqku+dBlJNhoUivPwCzjdjZlcuHh8LW88BpR3TOkX7TXeOwgkj2auYtT1mW+bWyp2TQaFuN7lDKbMNkIw0sJcPWpb/lQU8vWUQu66PDlumN8JHBhDEt4AyzwCJV2h7EFb6890kDAZVngwQm3FATIf9TMxfn28cvzbNJ6FwZf1cZxpAS0KukvJeoy3XDcdGPI9XWhrsHY37A8QczSQC3Jic+kC/HWfzU5djDJh8IBiZwIrIG+Gjmg0SoxSlWAZjaeM8HwTgPB5zuzC2pBwNHR6f10SHa8HNgiPucgR8lTm2VWMJj36KubfjU4KZlfVvP3Yu63vHIpvMvGJOPKNn0qq/v/oiSwU3PC/wz/6sjjD8kkkHNTmj0moQbUoYKdafLYXN9OqxTjKjMrSRVTd4lWW8Gvm9dCyVwB4hx4H1KENjQlIGM0JvLBTnTU6FrmHoRVe7yioljwLO3PqJCWf8H04cqyOYcfdFQgHR6K2wQV4=
  - secure: ScXm7HySA4cHTZ4m+oaciVR/UAKABvX6m512mP9big2vrrRAooWQK3gG6yyKt0riqyCu40PWnZ4hk8JswluJ6p1y7rFRBvTCJktLjjSSfPkwe8GLrzwQAiv23XKf2CqLG6o4+GTazpcuLOPEzsy/svXKiZCB7UKJ+gt8GH2LM8b7hAv6gJpjEoFspNEEb/9SGUOVSO0ONM7NYzDm+Hwn9xiiUeKPFz+EOhAgrnRXP9HjvtUH9BR0ZPDx/VoOmyGPfO8KpSMawESc2FofqNR/3GI9xHv8rnkNotyUv92hP2roSbb1LDqVq1K+s52gY5vRol0JxCitcNosNjsCKQZKYnHwzUzbtzMDNvpjLcBZ/cM6SnISBFpvwDn2/Fsrm2D478f7GiItrzFQtTVyTv7kXxd/xyLJN4SXfIRD9qruY9JKeP6QpIYwQUH8HBegRFY+qufclQhHLmSz4l2IzzNCHsAO74gRYy2ssRIKtcqYCHvBDT0L5bTYMDlW+VE/b/HsLj9fxfAh4SSJ+dWo3dl5gWftViDzBOeFGt2yKqb/Iv7jFyJEvs0Uc0sG95BtXEWK9U2icUzt84bsnkkXn0GGKcfquTDCLv3gIrgEuyRX7ZnSip1W+KSmICzlhnUi8dIBTSd/bnzdZNUFVBdz+l/g1yCSuOmVZaaWJ74FLNdvSdc=
